# Generated by Django 5.1.2 on 2024-11-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                ("directorID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("yearOfBirth", models.DateField()),
                ("yearOfDeath", models.DateField(blank=True, null=True)),
                (
                    "mostPopularFilm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("genreID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                ("hallID", models.AutoField(primary_key=True, serialize=False)),
                ("numberOfSeats", models.IntegerField()),
                ("is3D", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("priceID", models.AutoField(primary_key=True, serialize=False)),
                ("basePrice", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "VIPPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("yearOfBirth", models.DateField()),
                ("phoneNumber", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("filmID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("minAge", models.IntegerField(default=3)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "directorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema.director",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilmGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.film"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.genre"
                    ),
                ),
            ],
            options={
                "unique_together": {("film", "genre")},
            },
        ),
        migrations.AddField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(through="cinema.FilmGenre", to="cinema.genre"),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                ("seatID", models.AutoField(primary_key=True, serialize=False)),
                ("rowNumber", models.IntegerField()),
                ("numberOfSeat", models.IntegerField()),
                ("isVIP", models.BooleanField(default=False)),
                (
                    "hallID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.hall"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("sessionID", models.AutoField(primary_key=True, serialize=False)),
                ("dateAndTime", models.DateTimeField()),
                ("duration", models.TimeField()),
                (
                    "filmID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.film"
                    ),
                ),
                (
                    "hallID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.hall"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticketID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "priceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.price"
                    ),
                ),
                (
                    "seatID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.seat"
                    ),
                ),
                (
                    "sessionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.session"
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.user"
                    ),
                ),
            ],
        ),
    ]
